[
   {
      "Alumno":"Pedro",
      "Nota":7.09,
      "Ranking":89,
     },
   {
      "Alumno":"Miguel",
      "Nota":10,
      "Ranking":160,
   },
   {
      "Alumno":"Patricia",
      "Nota":6.5,
      "Ranking":60,
   },
   {
      "Alumno":"Julia",
      "Nota":10
      "Ranking":180,
   },
   {
      "Alumno":"David",
      "Nota":9.5,
      "Ranking":140,
   },
   {
      "Alumno":"Victor",
      "Nota":6,
      "Ranking":50,
   },
   {
      "Alumno":"Sara",
      "Nota":7.65,
      "Ranking":100,
   },
   {
      "Alumno":"Carlos",
      "Nota":8.2,
      "Ranking":120,
   },
  {
      "Alumno":"Raquel",
      "Nota":3.5,
      "Ranking":20,
   },
   {
      "Alumno":"Ana",
      "Nota":7.75,
      "Ranking":90,
   }
]